# Exercise

In [ ]:
import numpy as np

## 1.
- ([[10, 20, 30, 40],
    [50, 60, 70, 80]])

In [ ]:
np.arange(1, 9).reshape(2, 4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2.
- a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
- 값 7 인덱싱
- 값 14 인덱싱
- 배열 [6, 7] 슬라이싱
- 배열 [7, 12] 슬라이싱
- 배열 [[3, 4], [8, 9]] 슬라이싱

In [ ]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a[1, 2]

7

In [ ]:
a[-1, -1]

14

In [ ]:
a[1, 1:3]

array([6, 7])

In [ ]:
a[1:, 2]

array([ 7, 12])

In [ ]:
a[:2, 3:]

array([[3, 4],
       [8, 9]])

## 3. 행렬 a를 1차원 벡터 f로 변환
- 3의 배수
- 4로 나누면 1이 남는 수
- 3으로 나누어지고 4로 나누면 1이 남는 수

In [ ]:
f = a.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [ ]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [ ]:
f[np.logical_and(f % 3 == 0, f % 4 == 1)]

array([9])

## 4. [[2, 1, 0, 0, 0],[3, 2, 1, 0, 0],[0, 3, 2, 1, 0],[0, 0, 3, 2, 1],[0, 0, 0, 3, 2]]

In [ ]:
np.eye(5, 5, k = -1) * 3 + np.eye(5, 5) * 2 + np.eye(5, 5, k = 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

## 5. 0~10 랜덤 실수, 5 * 6 행렬
- 최대값
- 각 행의 합
- 각 행의 최대값
- 각 열의 평균
- 각 열의 최소값

In [ ]:
np.random.seed(2021)
e = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
e

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [ ]:
np.max(e)

9.9724

In [ ]:
np.sum(e, axis = 1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [ ]:
np.max(e, axis = 1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [ ]:
np.mean(e, axis = 0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [ ]:
np.min(e, axis = 0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

## 6. 첫번째 행: 학번, 두번째 행: 영어 성적, 세번째 행: 수학 성적 - 영어 성적 기준 각 열 재정렬

In [ ]:
g = np.array([[1, 2, 3, 4],
             [46, 99, 100, 71],
             [81, 59, 90, 100]])

In [ ]:
np.sort(g, axis = 1)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [ ]:
s = np.argsort(g[1])
s

array([0, 3, 1, 2])

In [ ]:
s[::-1]

array([2, 1, 3, 0])

In [ ]:
g[:, s]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [ ]:
g[:, np.argsort(g[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## 7. 주사위 100번 가상 실험, 나온 숫자의 평균

In [ ]:
np.random.seed(2021)
d = np.random.randint(1, 7, 100)
d

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [ ]:
np.mean(d)

3.7

## 8. 주식 10,000원, 일간 수익률 기대값 0%, 표준편차 1% 표준 정규 분포, 250일 간 무작위 주가 생성

In [ ]:
np.random.seed(2021)
p = 10000
r = np.random.normal(0, 1, 10)
for i in range(10):
    p += np.round(p * r[i] * 0.01)
    print(p, end = ', ')

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [ ]:
np.random.seed(2021)
p_list = []
r = np.random.normal(0, 1, 250)
p = 10000
for i in range(250):
    p += np.round(p * r[i] * 0.01)
    p_list.append(p)
p_array = np.array(p_list, int)

In [ ]:
print(p_array[:10])

[10149 10218 10175 10093 10149 10077 10191 10257 10268 10311]


In [ ]:
print(p_array[-10:])

[12072 12210 12255 12359 12292 12262 12136 12010 11984 12113]
