# NumPy(Numerical Python) Part 1.

In [1]:
# de facto standard(사실상 표준)
import numpy as np

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: x * 3, a))

[3, 6, 9]

In [5]:
b = np.array([1, 2, 3])
b * 3

array([3, 6, 9])

## 1. NumPy Dimensional Array

In [6]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array Shape

In [14]:
# Vector(1차원)
vector = np.array([1, 4, 5, 8])
vector.shape

(4,)

In [16]:
# Matrix(2차원)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [18]:
# Tensor(3차원 이상)
tensor = np.arange(1, 25).reshape(2, 3, 4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [19]:
tensor.shape

(2, 3, 4)

In [20]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [21]:
# Element의 개수
vector.size, matrix.size, tensor.size

(4, 6, 24)

### Data Type
- float32: 32Bit - Single Precision
- float64: 64Bit - Double Precision

In [28]:
a = np.array([1, 2, 3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [24]:
b = np.array([1, 2, 3], np.int16)
b

array([1, 2, 3], dtype=int16)

### Reshape

In [25]:
matrix.shape

(2, 3)

In [26]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [27]:
matrix.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# -1은 NumPy가 알아서 맞춰줌(단, 사이즈 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [30]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
matrix.reshape(3, -1).shape

(3, 2)

In [32]:
tensor.shape

(2, 3, 4)

In [33]:
tensor.reshape(4, -1).shape

(4, 6)

In [34]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [35]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [36]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Flatten

In [43]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [38]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [39]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
matrix.shape

(2, 3)

In [41]:
matrix[0][1]

2

In [42]:
matrix[0, 1]

2

In [44]:
tensor[1, 1, 2]

19

### Slicing

In [45]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
# 5, 6, 9, 10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [47]:
# 5, 6, 7, 9, 10, 11
b[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [50]:
# 1, 3, 9, 11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [52]:
# X는 앞 3열, y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))